### ISSUE TITLE
How to connect with database?

### ISSUE THREAD

**Issue by panupong51** [gmaccario/simple-mvc-php-framework#23]
Could you show the example for CRUD ?

**Comment by gmaccario** [comment]
Hello @panupong51 

It was intentional to not show any DB-related flow because there are several mechanisms to do that, for example, you use Doctrine or Eloquent, or simply use the PDO. Moreover, the goal of my repository/tutorial was to create a simple MVC example, not a complete solution. You are free to choose your favorite way to interact with the DB and use it in your controllers.

Best.
