### ISSUE TITLE
routing not working

### ISSUE THREAD

**Issue by sangasangasanga** [gmaccario/simple-mvc-php-framework#4]
Hi, i followed your guide to create. It showed route issue. So i downloaded your code and tried. It kept showing routes issues. I put the project in xampp/htdocs. Kindly assist
![image](https://user-images.githubusercontent.com/34553270/133053660-696afcca-c83a-4312-a9fb-051269953b34.png)

**Comment by gmaccario** [comment]
Hello @sangasangasanga 

did you set up the URL_SUBFOLDER constant in the config file? https://github.com/gmaccario/simple-mvc-php-framework/blob/master/config/config.php

**Comment by gmaccario** [comment]
Hey @sangasangasanga 

Another note: the route should be 
http://localhost/simple-mvc-php-framework-master/

and NOT 

http://localhost/simple-mvc-php-framework-master/homepage

**Comment by sangasangasanga** [comment]
Hi, still doesn't work
![image](https://user-images.githubusercontent.com/34553270/133086538-f730ad54-539e-4f0d-a931-cc1b5d2d8b0b.png)
![image](https://user-images.githubusercontent.com/34553270/133086575-49a0540c-e31e-4597-a1af-8122ff37bdd9.png)
![image](https://user-images.githubusercontent.com/34553270/133086864-16e62c0a-06f6-4565-9d04-40c046ec23af.png)

**Comment by gmaccario** [comment]
Hi @sangasangasanga 

I fear there is something wrong with XAMPP configuration and the htaccess, but I am not sure, I do not use XAMPP for 10 years or more.

Please, try to modify the htaccess or check the router file and do some debug: https://github.com/gmaccario/simple-mvc-php-framework/blob/master/app/Router.php

Otherwise, feel free to send me your code via email or fork the project and I will take a look at it ASAP.

Sorry for the inconvenience.

**Comment by sangasangasanga** [comment]
Hi, I tried to debug for a while now and am not sure of issue.
Can i send it to you via email?

**Comment by gmaccario** [comment]
> Hi, I tried to debug for a while now and am not sure of issue.
> Can i send it to you via email?

Hey @sangasangasanga 

yes sure send it to me via email, I will take a look at it ASAP.

**Comment by sangasangasanga** [comment]
Sorry, may i have your email?

**Comment by gmaccario** [comment]
> Sorry, may i have your email? Thank you so much

github@giuseppemaccario.com

**Comment by sangasangasanga** [comment]
Sent, thank you

**Comment by gmaccario** [comment]
Hi @sangasangasanga 

In my project, I created a new (sub)folder called _simple-mvc-php-framework-master_ and I copied your code there.
Then I set up the URL_SUBFOLDER constant in the config as you did.

Here the results:
![daef19857573a2bcbc68ba159a0afe66](https://user-images.githubusercontent.com/5927739/133100847-aa2f3440-6863-4587-b146-5240ad54e89f.png)
![f355e9a7bb8d3581dd8f85255b356ced](https://user-images.githubusercontent.com/5927739/133100855-17dae5df-68c1-4166-81fb-5daf69c3e512.png)

As you can see the MVC is still working well, for that reason I assume that the error is in your XAMPP configuration, probably due to a mismatch between XAMPP and the htaccess. 

Unfortunately, I don't use XAMPP, then it's up to you to debug your environment or... move on on a different MVC boilerplate (Github is full of examples).

If you eventually find a solution for your issue, please send me the solution so we can help other people in the future.

Many thanks.
